//! The file a JavaScript engine runs to compute the golden hash.
//!
//! An engine shell (SpiderMonkey's `js`, JavaScriptCore's `jsc`) has no file
//! or module API that node shares, and may have no `atob`. So each run gets
//! one generated script that embeds everything as base64 (the law's wasm, the
//! container and the take), decodes it with its own small decoder, and uses
//! only `WebAssembly`, typed arrays, `BigInt` and `print` (or `console.log`
//! under node). The script drives the law's C ABI in the same order the
//! native harness does (see [`crate::run::compute`]):
//!
//! 1. it checks its decoder against RFC 4648's test vectors, its SHA-256
//!    against FIPS 180's, and the decoded lengths against the ones generated
//!    here;
//! 2. it hashes the exact bytes it is about to compile, requires the
//!    generator's SHA-256, and prints it as `wasm-sha256`;
//! 3. it instantiates the wasm with no imports, and checks the law version;
//! 4. `law_ingest(container)`, `law_admit_take(take)`, `law_snapshot`;
//! 5. `law_step` the golden's number of times, and `law_snapshot` again;
//! 6. it prints the law version, the steps, the snapshot's length and the
//!    computed hash, all read from the instance, and throws unless the two
//!    snapshots and the golden are one hash.
//!
//! An uncaught exception exits every engine with a non-zero status. CI does
//! not take the script's word for it: it compares the printed hash with the
//! golden file itself, `wasm-sha256` with the artifact's own digest, and the
//! law version and snapshot length with the golden file's. A shell that only
//! printed the expected lines would still have to produce the SHA-256 of
//! the artifact, and CI runs no shell whose files are not pinned
//! (`.github/engines/`).
//!
//! Generation is deterministic: the output depends only on its inputs, never
//! on a clock, a path or the host.

/// What the script is for: the check, or a negative control that must fail.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Role {
    Check,
    /// Built from a take changed by one sample: a run of it must fail.
    NegativeControl,
}

/// Everything one generated script embeds.
#[derive(Clone, Debug)]
pub struct Script<'a> {
    pub role: Role,
    pub wasm: &'a [u8],
    pub container: &'a [u8],
    pub take: &'a [u8],
    pub steps: u64,
    pub law_version: u32,
    /// The golden hash, as the committed golden file records it.
    pub golden: [u8; 32],
}

const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// Standard base64 with padding (RFC 4648, section 4).
pub fn base64(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b = [
            chunk[0],
            chunk.get(1).copied().unwrap_or(0),
            chunk.get(2).copied().unwrap_or(0),
        ];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        for (i, shift) in [18u32, 12, 6, 0].into_iter().enumerate() {
            if i <= chunk.len() {
                out.push(char::from(ALPHABET[((n >> shift) & 63) as usize]));
            } else {
                out.push('=');
            }
        }
    }
    out
}

/// The script's text before its data is filled in. `@NAME@` marks each slot.
const TEMPLATE: &str = r#"// si-jam-sessions: the golden check, run by a JavaScript engine.
// Generated by `cargo run -p golden --bin engine-js`; do not edit. It embeds
// the law's wasm, the container and the take as base64, and needs nothing
// from its host but WebAssembly, typed arrays, BigInt and print (or
// console.log under node).
// @ROLE@
// wasm: @WASM_LEN@ bytes, sha256 @WASM_SHA256@
(function () {
  "use strict";
  var say = typeof print === "function" ? print : console.log;

  var ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  var VALUE = new Int16Array(128);
  var v;
  for (v = 0; v < 128; v++) VALUE[v] = -1;
  for (v = 0; v < 64; v++) VALUE[ALPHABET.charCodeAt(v)] = v;

  // Standard base64 with padding (RFC 4648, section 4). Anything else throws.
  function decode(text) {
    if (text.length % 4 !== 0) throw new Error("base64: the length is not a multiple of 4");
    var pad = 0;
    if (text.length > 0 && text.charCodeAt(text.length - 1) === 61) pad++;
    if (text.length > 1 && text.charCodeAt(text.length - 2) === 61) pad++;
    var out = new Uint8Array(text.length / 4 * 3 - pad);
    var o = 0;
    for (var i = 0; i < text.length; i += 4) {
      var n = 0;
      for (var k = 0; k < 4; k++) {
        var c = text.charCodeAt(i + k);
        var d = c < 128 ? VALUE[c] : -1;
        if (c === 61 && i + k >= text.length - pad) d = 0;
        if (d < 0) throw new Error("base64: a bad character at " + (i + k));
        n = n * 64 + d;
      }
      if (o < out.length) out[o++] = (n >>> 16) & 255;
      if (o < out.length) out[o++] = (n >>> 8) & 255;
      if (o < out.length) out[o++] = n & 255;
    }
    return out;
  }

  function hex(bytes) {
    var s = "";
    for (var i = 0; i < bytes.length; i++) s += (bytes[i] < 16 ? "0" : "") + bytes[i].toString(16);
    return s;
  }

  // Printable ASCII as it is; any other byte as \xNN.
  function ascii(bytes) {
    var s = "";
    for (var i = 0; i < bytes.length; i++) {
      var b = bytes[i];
      s += b >= 32 && b < 127 ? String.fromCharCode(b) : "\\x" + (b < 16 ? "0" : "") + b.toString(16);
    }
    return s;
  }

  var VECTORS = [["", ""], ["Zg==", "f"], ["Zm8=", "fo"], ["Zm9v", "foo"],
                 ["Zm9vYg==", "foob"], ["Zm9vYmE=", "fooba"], ["Zm9vYmFy", "foobar"]];
  for (var t = 0; t < VECTORS.length; t++) {
    if (ascii(decode(VECTORS[t][0])) !== VECTORS[t][1]) {
      throw new Error("base64 self-test failed on '" + VECTORS[t][0] + "'");
    }
  }

  // SHA-256 (FIPS 180-4), in 32-bit integer operations only. The constants
  // were derived with exact integer arithmetic (the fractional parts of the
  // cube roots of the first 64 primes, and of the square roots of the first
  // 8), and the self-test below checks FIPS 180's examples.
  var K = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
    0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
    0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
    0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
    0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2
  ];
  function rotr(x, n) { return (x >>> n) | (x << (32 - n)); }
  function sha256(bytes) {
    var n = bytes.length;
    var blocks = Math.floor((n + 8) / 64) + 1;
    var m = new Uint8Array(blocks * 64);
    m.set(bytes);
    m[n] = 0x80;
    // The message length in bits, big-endian in the last eight bytes.
    var high = Math.floor(n / 0x20000000);
    var low = (n % 0x20000000) * 8;
    var end = blocks * 64;
    for (var i = 0; i < 4; i++) {
      m[end - 8 + i] = (high >>> (24 - 8 * i)) & 255;
      m[end - 4 + i] = (low >>> (24 - 8 * i)) & 255;
    }
    var hs = [0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19];
    var w = new Int32Array(64);
    for (var off = 0; off < end; off += 64) {
      var r;
      for (r = 0; r < 16; r++) {
        var j = off + 4 * r;
        w[r] = (m[j] << 24) | (m[j + 1] << 16) | (m[j + 2] << 8) | m[j + 3];
      }
      for (r = 16; r < 64; r++) {
        var x = w[r - 15], y = w[r - 2];
        w[r] = (w[r - 16] + (rotr(x, 7) ^ rotr(x, 18) ^ (x >>> 3)) + w[r - 7] +
                (rotr(y, 17) ^ rotr(y, 19) ^ (y >>> 10))) | 0;
      }
      var a = hs[0], b = hs[1], c = hs[2], d = hs[3], e = hs[4], f = hs[5], g = hs[6], h = hs[7];
      for (r = 0; r < 64; r++) {
        var t1 = (h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + K[r] + w[r]) | 0;
        var t2 = ((rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c))) | 0;
        h = g; g = f; f = e; e = (d + t1) | 0; d = c; c = b; b = a; a = (t1 + t2) | 0;
      }
      hs[0] = (hs[0] + a) | 0; hs[1] = (hs[1] + b) | 0; hs[2] = (hs[2] + c) | 0; hs[3] = (hs[3] + d) | 0;
      hs[4] = (hs[4] + e) | 0; hs[5] = (hs[5] + f) | 0; hs[6] = (hs[6] + g) | 0; hs[7] = (hs[7] + h) | 0;
    }
    var out = "";
    for (var q = 0; q < 8; q++) out += ("0000000" + (hs[q] >>> 0).toString(16)).slice(-8);
    return out;
  }
  function bytesOf(text) {
    var b = new Uint8Array(text.length);
    for (var i = 0; i < text.length; i++) b[i] = text.charCodeAt(i);
    return b;
  }
  var DIGESTS = [
    ["", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],
    ["abc", "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"],
    ["abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
     "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"]
  ];
  for (var u = 0; u < DIGESTS.length; u++) {
    if (sha256(bytesOf(DIGESTS[u][0])) !== DIGESTS[u][1]) {
      throw new Error("sha256 self-test failed on '" + DIGESTS[u][0] + "'");
    }
  }

  var wasm = decode("@WASM@");
  var container = decode("@CONTAINER@");
  var take = decode("@TAKE@");
  var steps = @STEPS@;
  var golden = "@GOLDEN@";
  if (wasm.length !== @WASM_LEN@ || container.length !== @CONTAINER_LEN@ || take.length !== @TAKE_LEN@) {
    throw new Error("the decoded lengths are not the generator's");
  }

  // The SHA-256 of the very bytes compiled below. CI compares it with the
  // artifact's own digest, so the lines this script prints are tied to that
  // artifact and not only to this script's text.
  var wasmSha256 = sha256(wasm);
  if (wasmSha256 !== "@WASM_SHA256@") {
    throw new Error("the decoded wasm has sha256 " + wasmSha256 + ", not the generator's");
  }
  var law = new WebAssembly.Instance(new WebAssembly.Module(wasm), {}).exports;
  say("wasm-sha256 " + wasmSha256);
  // Any call may grow linear memory, which detaches a view, so each read
  // takes a fresh one.
  function memory() { return new Uint8Array(law.memory.buffer); }
  function reason() {
    var p = law.law_refusal_ptr() >>> 0;
    return ascii(memory().subarray(p, p + (law.law_refusal_len() >>> 0)));
  }
  function ok(status, what) {
    if (status !== 0) throw new Error(what + " refused with status " + status + ": " + reason());
  }
  function pass(bytes, verb, what) {
    var ptr = law.law_alloc(bytes.length) >>> 0;
    if (ptr === 0) throw new Error("law_alloc(" + bytes.length + ") returned null");
    memory().set(bytes, ptr);
    var status = verb(ptr, bytes.length);
    ok(law.law_free(ptr, bytes.length), "law_free after " + what);
    ok(status, what);
  }
  function snapshotHash() {
    ok(law.law_snapshot(), "law_snapshot");
    var p = law.law_hash_ptr() >>> 0;
    return hex(memory().subarray(p, p + 32));
  }

  if (law.law_version() !== @LAW_VERSION@) {
    throw new Error("the wasm is law version " + law.law_version() + ", the golden's is @LAW_VERSION@");
  }
  say("law-version " + law.law_version());
  pass(container, law.law_ingest, "law_ingest");
  pass(take, law.law_admit_take, "law_admit_take");
  var before = snapshotHash();
  for (var s = 0; s < steps; s++) {
    var status = law.law_step();
    if (status !== 0) ok(status, "law_step " + s);
  }
  if (law.law_steps() !== BigInt(steps)) throw new Error("law_steps reads " + law.law_steps());
  var computed = snapshotHash();
  say("steps " + steps);
  say("snapshot-bytes " + (law.law_snapshot_len() >>> 0));
  say("computed " + computed);
  say("golden " + golden);
  if (before !== computed) throw new Error("stepping moved the hash: " + before + " then " + computed);
  if (computed !== golden) throw new Error("golden mismatch: computed " + computed + ", golden " + golden);
  say("golden check passed");
})();
"#;

/// The generated script.
pub fn render(script: &Script<'_>) -> String {
    let role = match script.role {
        Role::Check => "The check: it must print the golden hash and pass.",
        Role::NegativeControl => {
            "A negative control: its take has one note one sample late, so it must fail."
        }
    };
    let slots = [
        ("@ROLE@", role.to_owned()),
        ("@WASM_LEN@", script.wasm.len().to_string()),
        (
            "@WASM_SHA256@",
            crate::run::hex(&crate::run::sha256(script.wasm)),
        ),
        ("@WASM@", base64(script.wasm)),
        ("@CONTAINER_LEN@", script.container.len().to_string()),
        ("@CONTAINER@", base64(script.container)),
        ("@TAKE_LEN@", script.take.len().to_string()),
        ("@TAKE@", base64(script.take)),
        ("@STEPS@", script.steps.to_string()),
        ("@GOLDEN@", crate::run::hex(&script.golden)),
        ("@LAW_VERSION@", script.law_version.to_string()),
    ];
    let mut out = TEMPLATE.to_owned();
    for (slot, value) in slots {
        out = out.replace(slot, &value);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// RFC 4648, section 10.
    #[test]
    fn base64_matches_the_rfc_vectors() {
        let vectors = [
            ("", ""),
            ("f", "Zg=="),
            ("fo", "Zm8="),
            ("foo", "Zm9v"),
            ("foob", "Zm9vYg=="),
            ("fooba", "Zm9vYmE="),
            ("foobar", "Zm9vYmFy"),
        ];
        for (plain, encoded) in vectors {
            assert_eq!(base64(plain.as_bytes()), encoded);
        }
        assert_eq!(base64(&[0xFF, 0xFE, 0xFD]), "//79");
        assert_eq!(base64(&[0, 0, 0, 0]), "AAAAAA==");
    }

    fn script(role: Role) -> Script<'static> {
        Script {
            role,
            wasm: b"\0asm\x01\0\0\0",
            container: b"SJIN",
            take: b"SJTK\x01",
            steps: 252_917,
            law_version: 99,
            golden: [0xAB; 32],
        }
    }

    /// The base64 text between `decode("` and the next `")`, in order.
    fn embedded(js: &str) -> Vec<&str> {
        js.split("decode(\"")
            .skip(1)
            .map(|rest| rest.split("\")").next().unwrap())
            .collect()
    }

    #[test]
    fn every_slot_is_filled_and_the_data_is_what_went_in() {
        let js = render(&script(Role::Check));
        assert!(!js.contains('@'), "an unfilled slot");
        let data = embedded(&js);
        assert_eq!(
            data,
            [
                base64(b"\0asm\x01\0\0\0"),
                base64(b"SJIN"),
                base64(b"SJTK\x01")
            ]
        );
        assert!(js.contains("var steps = 252917;"));
        assert!(js.contains(&format!("var golden = \"{}\";", "ab".repeat(32))));
        assert!(js.contains("law.law_version() !== 99"));
        assert!(js.contains("The check: it must print the golden hash and pass."));
        let control = render(&script(Role::NegativeControl));
        assert!(control.contains("A negative control"));
    }

    /// The first `count` primes.
    fn primes(count: usize) -> Vec<u128> {
        let mut out: Vec<u128> = Vec::new();
        let mut k = 2u128;
        while out.len() < count {
            if out
                .iter()
                .take_while(|&&p| p * p <= k)
                .all(|&p| !k.is_multiple_of(p))
            {
                out.push(k);
            }
            k += 1;
        }
        out
    }

    /// The integer cube root: the largest `r` with `r^3 <= n`.
    fn icbrt(n: u128) -> u128 {
        let (mut lo, mut hi) = (0u128, 1u128 << 43);
        while lo < hi {
            let mid = (lo + hi).div_ceil(2);
            if mid.checked_pow(3).is_some_and(|c| c <= n) {
                lo = mid;
            } else {
                hi = mid - 1;
            }
        }
        lo
    }

    /// The script's SHA-256 constants, derived here with exact integer roots
    /// (FIPS 180-4, 4.2.2 and 5.3.3), and its self-test digests, checked with
    /// the Rust `sha2` crate: the JavaScript is checked without a JavaScript
    /// engine, and again by its own self-test inside each one.
    #[test]
    fn the_scripts_sha256_constants_and_vectors_are_right() {
        let p = primes(64);
        let k: Vec<String> = p
            .iter()
            .map(|&p| format!("0x{:08x}", icbrt(p << 96) & 0xFFFF_FFFF))
            .collect();
        for row in k.chunks(8) {
            assert!(TEMPLATE.contains(&row.join(", ")), "a K row: {row:?}");
        }
        assert_eq!(k[0], "0x428a2f98");
        assert_eq!(k[63], "0xc67178f2");
        let h: Vec<String> = p[..8]
            .iter()
            .map(|&p| format!("0x{:08x}", (p << 64).isqrt() & 0xFFFF_FFFF))
            .collect();
        assert!(TEMPLATE.contains(&format!("var hs = [{}];", h.join(", "))));
        for (text, digest) in [
            (
                "",
                "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            ),
            (
                "abc",
                "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            ),
            (
                "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq",
                "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1",
            ),
        ] {
            assert_eq!(
                crate::run::hex(&crate::run::sha256(text.as_bytes())),
                digest
            );
            assert!(TEMPLATE.contains(digest), "the self-test holds {digest}");
        }
    }

    /// The script hashes the bytes it hands to `WebAssembly.Module`, requires
    /// the generator's digest, and prints it for CI to compare with the
    /// artifact.
    #[test]
    fn the_script_proves_which_wasm_it_instantiated() {
        let js = render(&script(Role::Check));
        let digest = crate::run::hex(&crate::run::sha256(b"\0asm\x01\0\0\0"));
        assert!(js.contains(&format!("if (wasmSha256 !== \"{digest}\")")));
        assert!(js.contains("say(\"wasm-sha256 \" + wasmSha256);"));
        let hashed = TEMPLATE.find("var wasmSha256 = sha256(wasm);").unwrap();
        let compiled = TEMPLATE.find("new WebAssembly.Module(wasm)").unwrap();
        assert!(hashed < compiled, "hashed before it is compiled");
        assert_eq!(TEMPLATE.matches("new WebAssembly.Module(").count(), 1);
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(render(&script(Role::Check)), render(&script(Role::Check)));
    }

    /// The script reaches its host only through `print` or `console.log`, and
    /// the law only through `WebAssembly`: no module system, no file, no
    /// clock, no randomness, no host decoder.
    #[test]
    fn the_script_uses_nothing_but_webassembly_and_print() {
        for forbidden in [
            "require",
            "import ",
            "import(",
            "export ",
            "process",
            "Buffer",
            "atob",
            "btoa",
            "TextDecoder",
            "TextEncoder",
            "fetch",
            "readFile",
            "load(",
            "Date",
            "random",
            "performance",
            "setTimeout",
            "globalThis",
            "eval",
            "Function(",
        ] {
            assert!(
                !TEMPLATE.contains(forbidden),
                "the template uses {forbidden}"
            );
        }
        assert!(TEMPLATE.contains("new WebAssembly.Instance(new WebAssembly.Module(wasm), {})"));
        assert!(TEMPLATE.contains("typeof print === \"function\" ? print : console.log"));
    }
}
