//! The file a JavaScript engine runs to compute the golden hash.
//!
//! An engine shell (SpiderMonkey's `js`, JavaScriptCore's `jsc`) has no file
//! or module API that node shares, and may have no `atob`. So each run gets
//! one generated script that embeds everything as base64 (the law's wasm, the
//! container and the take), decodes it with its own small decoder, and uses
//! only `WebAssembly`, typed arrays, `BigInt` and `print` (or `console.log`
//! under node). The script drives the law's C ABI in the same order the
//! native harness does (see [`crate::run::compute`]):
//!
//! 1. it checks its decoder against RFC 4648's test vectors, and the decoded
//!    lengths against the ones generated here;
//! 2. it instantiates the wasm with no imports, and checks the law version;
//! 3. `law_ingest(container)`, `law_admit_take(take)`, `law_snapshot`;
//! 4. `law_step` the golden's number of times, and `law_snapshot` again;
//! 5. it prints the computed hash and the golden's, and throws unless the two
//!    snapshots and the golden are one hash.
//!
//! An uncaught exception exits every engine with a non-zero status. CI also
//! compares the printed hash with the golden file itself.
//!
//! Generation is deterministic: the output depends only on its inputs, never
//! on a clock, a path or the host.

/// What the script is for: the check, or a negative control that must fail.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Role {
    Check,
    /// Built from a take changed by one sample: a run of it must fail.
    NegativeControl,
}

/// Everything one generated script embeds.
#[derive(Clone, Debug)]
pub struct Script<'a> {
    pub role: Role,
    pub wasm: &'a [u8],
    pub container: &'a [u8],
    pub take: &'a [u8],
    pub steps: u64,
    pub law_version: u32,
    /// The golden hash, as the committed golden file records it.
    pub golden: [u8; 32],
}

const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

/// Standard base64 with padding (RFC 4648, section 4).
pub fn base64(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len().div_ceil(3) * 4);
    for chunk in bytes.chunks(3) {
        let b = [
            chunk[0],
            chunk.get(1).copied().unwrap_or(0),
            chunk.get(2).copied().unwrap_or(0),
        ];
        let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
        for (i, shift) in [18u32, 12, 6, 0].into_iter().enumerate() {
            if i <= chunk.len() {
                out.push(char::from(ALPHABET[((n >> shift) & 63) as usize]));
            } else {
                out.push('=');
            }
        }
    }
    out
}

/// The script's text before its data is filled in. `@NAME@` marks each slot.
const TEMPLATE: &str = r#"// si-jam-sessions: the golden check, run by a JavaScript engine.
// Generated by `cargo run -p golden --bin engine-js`; do not edit. It embeds
// the law's wasm, the container and the take as base64, and needs nothing
// from its host but WebAssembly, typed arrays, BigInt and print (or
// console.log under node).
// @ROLE@
// wasm: @WASM_LEN@ bytes, sha256 @WASM_SHA256@
(function () {
  "use strict";
  var say = typeof print === "function" ? print : console.log;

  var ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  var VALUE = new Int16Array(128);
  var v;
  for (v = 0; v < 128; v++) VALUE[v] = -1;
  for (v = 0; v < 64; v++) VALUE[ALPHABET.charCodeAt(v)] = v;

  // Standard base64 with padding (RFC 4648, section 4). Anything else throws.
  function decode(text) {
    if (text.length % 4 !== 0) throw new Error("base64: the length is not a multiple of 4");
    var pad = 0;
    if (text.length > 0 && text.charCodeAt(text.length - 1) === 61) pad++;
    if (text.length > 1 && text.charCodeAt(text.length - 2) === 61) pad++;
    var out = new Uint8Array(text.length / 4 * 3 - pad);
    var o = 0;
    for (var i = 0; i < text.length; i += 4) {
      var n = 0;
      for (var k = 0; k < 4; k++) {
        var c = text.charCodeAt(i + k);
        var d = c < 128 ? VALUE[c] : -1;
        if (c === 61 && i + k >= text.length - pad) d = 0;
        if (d < 0) throw new Error("base64: a bad character at " + (i + k));
        n = n * 64 + d;
      }
      if (o < out.length) out[o++] = (n >>> 16) & 255;
      if (o < out.length) out[o++] = (n >>> 8) & 255;
      if (o < out.length) out[o++] = n & 255;
    }
    return out;
  }

  function hex(bytes) {
    var s = "";
    for (var i = 0; i < bytes.length; i++) s += (bytes[i] < 16 ? "0" : "") + bytes[i].toString(16);
    return s;
  }

  // Printable ASCII as it is; any other byte as \xNN.
  function ascii(bytes) {
    var s = "";
    for (var i = 0; i < bytes.length; i++) {
      var b = bytes[i];
      s += b >= 32 && b < 127 ? String.fromCharCode(b) : "\\x" + (b < 16 ? "0" : "") + b.toString(16);
    }
    return s;
  }

  var VECTORS = [["", ""], ["Zg==", "f"], ["Zm8=", "fo"], ["Zm9v", "foo"],
                 ["Zm9vYg==", "foob"], ["Zm9vYmE=", "fooba"], ["Zm9vYmFy", "foobar"]];
  for (var t = 0; t < VECTORS.length; t++) {
    if (ascii(decode(VECTORS[t][0])) !== VECTORS[t][1]) {
      throw new Error("base64 self-test failed on '" + VECTORS[t][0] + "'");
    }
  }

  var wasm = decode("@WASM@");
  var container = decode("@CONTAINER@");
  var take = decode("@TAKE@");
  var steps = @STEPS@;
  var golden = "@GOLDEN@";
  if (wasm.length !== @WASM_LEN@ || container.length !== @CONTAINER_LEN@ || take.length !== @TAKE_LEN@) {
    throw new Error("the decoded lengths are not the generator's");
  }

  var law = new WebAssembly.Instance(new WebAssembly.Module(wasm), {}).exports;
  // Any call may grow linear memory, which detaches a view, so each read
  // takes a fresh one.
  function memory() { return new Uint8Array(law.memory.buffer); }
  function reason() {
    var p = law.law_refusal_ptr() >>> 0;
    return ascii(memory().subarray(p, p + (law.law_refusal_len() >>> 0)));
  }
  function ok(status, what) {
    if (status !== 0) throw new Error(what + " refused with status " + status + ": " + reason());
  }
  function pass(bytes, verb, what) {
    var ptr = law.law_alloc(bytes.length) >>> 0;
    if (ptr === 0) throw new Error("law_alloc(" + bytes.length + ") returned null");
    memory().set(bytes, ptr);
    var status = verb(ptr, bytes.length);
    ok(law.law_free(ptr, bytes.length), "law_free after " + what);
    ok(status, what);
  }
  function snapshotHash() {
    ok(law.law_snapshot(), "law_snapshot");
    var p = law.law_hash_ptr() >>> 0;
    return hex(memory().subarray(p, p + 32));
  }

  if (law.law_version() !== @LAW_VERSION@) {
    throw new Error("the wasm is law version " + law.law_version() + ", the golden's is @LAW_VERSION@");
  }
  say("law-version " + law.law_version());
  pass(container, law.law_ingest, "law_ingest");
  pass(take, law.law_admit_take, "law_admit_take");
  var before = snapshotHash();
  for (var s = 0; s < steps; s++) {
    var status = law.law_step();
    if (status !== 0) ok(status, "law_step " + s);
  }
  if (law.law_steps() !== BigInt(steps)) throw new Error("law_steps reads " + law.law_steps());
  var computed = snapshotHash();
  say("steps " + steps);
  say("snapshot-bytes " + (law.law_snapshot_len() >>> 0));
  say("computed " + computed);
  say("golden " + golden);
  if (before !== computed) throw new Error("stepping moved the hash: " + before + " then " + computed);
  if (computed !== golden) throw new Error("golden mismatch: computed " + computed + ", golden " + golden);
  say("golden check passed");
})();
"#;

/// The generated script.
pub fn render(script: &Script<'_>) -> String {
    let role = match script.role {
        Role::Check => "The check: it must print the golden hash and pass.",
        Role::NegativeControl => {
            "A negative control: its take has one note one sample late, so it must fail."
        }
    };
    let slots = [
        ("@ROLE@", role.to_owned()),
        ("@WASM_LEN@", script.wasm.len().to_string()),
        (
            "@WASM_SHA256@",
            crate::run::hex(&crate::run::sha256(script.wasm)),
        ),
        ("@WASM@", base64(script.wasm)),
        ("@CONTAINER_LEN@", script.container.len().to_string()),
        ("@CONTAINER@", base64(script.container)),
        ("@TAKE_LEN@", script.take.len().to_string()),
        ("@TAKE@", base64(script.take)),
        ("@STEPS@", script.steps.to_string()),
        ("@GOLDEN@", crate::run::hex(&script.golden)),
        ("@LAW_VERSION@", script.law_version.to_string()),
    ];
    let mut out = TEMPLATE.to_owned();
    for (slot, value) in slots {
        out = out.replace(slot, &value);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// RFC 4648, section 10.
    #[test]
    fn base64_matches_the_rfc_vectors() {
        let vectors = [
            ("", ""),
            ("f", "Zg=="),
            ("fo", "Zm8="),
            ("foo", "Zm9v"),
            ("foob", "Zm9vYg=="),
            ("fooba", "Zm9vYmE="),
            ("foobar", "Zm9vYmFy"),
        ];
        for (plain, encoded) in vectors {
            assert_eq!(base64(plain.as_bytes()), encoded);
        }
        assert_eq!(base64(&[0xFF, 0xFE, 0xFD]), "//79");
        assert_eq!(base64(&[0, 0, 0, 0]), "AAAAAA==");
    }

    fn script(role: Role) -> Script<'static> {
        Script {
            role,
            wasm: b"\0asm\x01\0\0\0",
            container: b"SJIN",
            take: b"SJTK\x01",
            steps: 252_917,
            law_version: 2,
            golden: [0xAB; 32],
        }
    }

    /// The base64 text between `decode("` and the next `")`, in order.
    fn embedded(js: &str) -> Vec<&str> {
        js.split("decode(\"")
            .skip(1)
            .map(|rest| rest.split("\")").next().unwrap())
            .collect()
    }

    #[test]
    fn every_slot_is_filled_and_the_data_is_what_went_in() {
        let js = render(&script(Role::Check));
        assert!(!js.contains('@'), "an unfilled slot");
        let data = embedded(&js);
        assert_eq!(
            data,
            [
                base64(b"\0asm\x01\0\0\0"),
                base64(b"SJIN"),
                base64(b"SJTK\x01")
            ]
        );
        assert!(js.contains("var steps = 252917;"));
        assert!(js.contains(&format!("var golden = \"{}\";", "ab".repeat(32))));
        assert!(js.contains("law.law_version() !== 2"));
        assert!(js.contains("The check: it must print the golden hash and pass."));
        let control = render(&script(Role::NegativeControl));
        assert!(control.contains("A negative control"));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(render(&script(Role::Check)), render(&script(Role::Check)));
    }

    /// The script reaches its host only through `print` or `console.log`, and
    /// the law only through `WebAssembly`: no module system, no file, no
    /// clock, no randomness, no host decoder.
    #[test]
    fn the_script_uses_nothing_but_webassembly_and_print() {
        for forbidden in [
            "require",
            "import ",
            "import(",
            "export ",
            "process",
            "Buffer",
            "atob",
            "btoa",
            "TextDecoder",
            "TextEncoder",
            "fetch",
            "readFile",
            "load(",
            "Date",
            "random",
            "performance",
            "setTimeout",
            "globalThis",
            "eval",
            "Function(",
        ] {
            assert!(
                !TEMPLATE.contains(forbidden),
                "the template uses {forbidden}"
            );
        }
        assert!(TEMPLATE.contains("new WebAssembly.Instance(new WebAssembly.Module(wasm), {})"));
        assert!(TEMPLATE.contains("typeof print === \"function\" ? print : console.log"));
    }
}
